language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t hikaritanabe -t tanabehikari/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tanabehikari/docker-react npm run test
